import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div>
          <div className="relative w-full flex items-center justify-center "/>
          <Navbar/>
        </div>
        
                {children}
        </body>
      
    </html>
  );
}

/// This is the layout component that will be used to wrap all the pages in the app you can use it in every page just by putting it here .